"use client";
import Image from "next/image";
import {useEffect,useMemo,useState} from "react";
import {BarChart3,CalendarDays,Check,Home,Leaf,LogOut,Map,Package,RefreshCw,ShieldCheck,ShoppingBag,Trees,Users,WalletCards,Wifi} from "lucide-react";

type Session={userId:string;username:string;name:string;farmId:string;role:string;permissions:string[];mustChangePassword:boolean};
type Farm={id:string;name:string;address:string|null;areaRai:number|null;plotCount:number;treeCount:number};
type Overview={farms:Farm[];selectedFarmId?:string;season:null|{id:string;name:string;status:string;startDate:string;endDate?:string};summary:{treeCount:number;openTaskCount:number;income:number;expense:number;productCount:number};tasks:Array<{id:string;title:string;status:string;scheduledAt:number|null}>};
type Tab="today"|"farms"|"trees"|"work"|"season"|"smart"|"harvest"|"money"|"report"|"stock"|"users";
const menu:[Tab,string,typeof Home][]=[["today","วันนี้",Home],["farms","สวน/แปลง",Map],["trees","ทะเบียนต้น",Trees],["work","งาน & ปฏิทิน",CalendarDays],["season","ฤดูผลิต",Leaf],["smart","สวนอัจฉริยะ",Wifi],["harvest","ผลผลิต & การขาย",ShoppingBag],["money","บัญชี",WalletCards],["report","วิเคราะห์ & GAP",BarChart3],["stock","คลังปัจจัยการผลิต",Package],["users","ผู้ใช้และสิทธิ์",Users]];
const permissionByTab:Partial<Record<Tab,string>>={farms:"farms.manage",trees:"trees.manage",work:"work.view",season:"dashboard.view",smart:"smartfarm.manage",harvest:"harvest.manage",money:"finance.view",report:"reports.view",stock:"inventory.view",users:"users.manage"};
const empty:Overview={farms:[],season:null,summary:{treeCount:0,openTaskCount:0,income:0,expense:0,productCount:0},tasks:[]};
const money=(n:number)=>new Intl.NumberFormat("th-TH",{style:"currency",currency:"THB",maximumFractionDigits:0}).format(n);

export default function LiveApp({session}:{session:Session}){
 const [tab,setTab]=useState<Tab>("today"),[data,setData]=useState<Overview>(empty),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=()=>{setLoading(true);setError("");fetch("/api/overview",{cache:"no-store"}).then(async r=>{const body=await r.json();if(!r.ok)throw new Error(body.error||"โหลดข้อมูลไม่สำเร็จ");setData(body)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))};
 useEffect(load,[]);
 const visible=menu.filter(([id])=>session.role==="admin"||!permissionByTab[id]||session.permissions.includes(permissionByTab[id]!));
 const farm=data.farms.find(x=>x.id===data.selectedFarmId)||data.farms[0];
 const logout=async()=>{await fetch("/api/auth/logout",{method:"POST"});location.reload()};
 const page=useMemo(()=>{
  if(tab==="today")return <Dashboard session={session} farm={farm} data={data} go={setTab}/>;
  if(tab==="farms")return <FarmsPage farms={data.farms} go={setTab}/>;
  if(tab==="users")return <UsersPage/>;
  const copy:Record<Exclude<Tab,"today"|"farms"|"users">,[string,string,string]>={trees:["ทะเบียนต้นทุเรียน","ยังไม่มีต้นทุเรียนในระบบ","เริ่มจากสร้างแปลงใน P2 แล้วเพิ่มต้นหรือนำเข้าทะเบียนต้น"],work:["งานในสวน & ปฏิทิน","ยังไม่มีงานที่บันทึกไว้","ระบบงานจริงจะเชื่อมแปลง ต้น ผู้รับผิดชอบ และฤดูผลิตใน P4"],season:["ฤดูการผลิต","ยังไม่ได้เปิดฤดูผลิต","การเปิด–ปิดฤดูและประวัติฤดูจะจัดทำใน P3"],smart:["สวนอัจฉริยะ","ยังไม่มีข้อมูลเฝ้าระวัง","ข้อมูลอากาศ สุขภาพต้น และเซนเซอร์จะเชื่อมใน P7"],harvest:["ผลผลิต & การขาย","ยังไม่มีรุ่นเก็บเกี่ยว","การเก็บเกี่ยว คัดเกรด ขาย และตรวจสอบย้อนกลับจะจัดทำใน P6"],money:["รายรับ–รายจ่าย","ยังไม่มีรายการบัญชี","รายการจริงจะเชื่อมงาน การซื้อ คลัง และฤดูผลิตใน P5"],report:["วิเคราะห์ & GAP","ยังไม่มีข้อมูลเพียงพอสำหรับรายงาน","รายงานจะคำนวณจากข้อมูลจริงและประวัติฤดูใน P8"],stock:["คลังปัจจัยการผลิต","ยังไม่มีสินค้าในคลัง","ทะเบียนสินค้า Lot และการซื้อเข้าคลังจะจัดทำใน P5"]};
  const [title,headline,detail]=copy[tab];return <EmptyPage title={title} headline={headline} detail={detail}/>;
 },[tab,data,farm,session]);
 return <div className="shell live-shell"><aside><button className="brand" onClick={()=>setTab("today")}><b><Leaf/></b><span><strong>น้องทุเรียน</strong><small>Durian Smart Farm</small></span></button><nav>{visible.map(([id,label,I])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}><I/>{label}</button>)}</nav><div className="session-card"><i>{session.name.slice(0,2)}</i><span><b>{session.name}</b><small>@{session.username} · {session.role==="admin"?"ผู้ดูแลระบบ":"ผู้ใช้งาน"}</small></span><button onClick={logout} aria-label="ออกจากระบบ"><LogOut/></button></div><div className="season-mini real"><small>ฤดูปัจจุบัน</small><strong>{data.season?.name||"ยังไม่ได้เปิดฤดูผลิต"}</strong></div></aside><main><header><strong>{farm?.name||"กำลังเตรียมข้อมูลสวน"}</strong><button className="refresh" onClick={load}><RefreshCw/> รีเฟรชข้อมูล</button></header><section className="content">{loading?<div className="loading-panel"><Leaf/> กำลังอ่านข้อมูลจริง...</div>:error?<div className="error-panel"><b>เชื่อมข้อมูลไม่สำเร็จ</b><span>{error}</span><button onClick={load}>ลองใหม่</button></div>:page}</section></main><div className="mobile-nav">{visible.filter(([id])=>["today","farms","work","money","users"].includes(id)).map(([id,label,I])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}><I/><span>{label.split(" ")[0]}</span></button>)}</div></div>
}

function Dashboard({session,farm,data,go}:{session:Session;farm?:Farm;data:Overview;go:(t:Tab)=>void}){return <><div className="hello"><div><small>ข้อมูลใช้งานจริง</small><h1>สวัสดีครับ {session.name} 👋</h1><p>{farm?`กำลังดูข้อมูล ${farm.name}`:"กำลังเตรียมข้อมูลสวนของคุณ"}</p></div></div><div className="hero clean"><div><em>ศูนย์บัญชาการสวนวันนี้</em><h2>{data.season?data.season.name:"เริ่มต้นจัดโครงสร้างสวน"}</h2><p>{data.season?"ข้อมูลใหม่จะเชื่อมกับฤดูปัจจุบัน":"ขั้นต่อไป: ตรวจข้อมูลสวน เพิ่มแปลง และเปิดฤดูผลิต"}</p><button className="light" onClick={()=>go("farms")}><Map/> ดูข้อมูลสวน</button></div><Image src="/nong-durian.png" alt="น้องทุเรียน" width={300} height={300}/></div><div className="stats"><Stat icon={<Trees/>} label="ต้นทุเรียน" value={String(data.summary.treeCount)} note="จากทะเบียนต้นจริง"/><Stat icon={<CalendarDays/>} label="งานที่ยังไม่เสร็จ" value={String(data.summary.openTaskCount)} note="จากงานในระบบ"/><Stat icon={<WalletCards/>} label="รายรับเดือนนี้" value={money(data.summary.income)} note="จากบัญชีจริง"/><Stat icon={<WalletCards/>} label="รายจ่ายเดือนนี้" value={money(data.summary.expense)} note="จากบัญชีจริง"/></div><div className="grid"><article className="panel"><div className="title"><h3>งานที่ต้องทำ</h3><button onClick={()=>go("work")}>ดูงาน →</button></div>{data.tasks.length?data.tasks.map(x=><div className="real-row" key={x.id}><Check/><span><b>{x.title}</b><small>{x.status}</small></span></div>):<MiniEmpty text="ยังไม่มีงานที่บันทึกไว้"/>}</article><article className="panel"><div className="title"><h3>เริ่มใช้งานจริง</h3></div><ol className="onboarding-list"><li className={farm?"done":""}>ตรวจชื่อและข้อมูลสวน</li><li>เพิ่มแปลงและทะเบียนต้น</li><li>เปิดฤดูการผลิต</li><li>เริ่มบันทึกงานและต้นทุน</li></ol></article></div></>}
function Stat({icon,label,value,note}:{icon:React.ReactNode;label:string;value:string;note:string}){return <article className="card"><b>{icon}</b><div><small>{label}</small><strong>{value}</strong><span>{note}</span></div></article>}
function FarmsPage({farms,go}:{farms:Farm[];go:(t:Tab)=>void}){return <><PageHead eyebrow="ข้อมูลจากฐานข้อมูลจริง" title="สวนของฉัน" detail="P0 รักษาข้อมูลสวนจริงและซ่อนข้อมูลตัวอย่างทั้งหมด"/><div className="farmgrid">{farms.map((f,i)=><article className="farm" key={f.id}><Map/><small>{i===0?"สวนหลัก":"สวนเพิ่มเติม"}</small><h2>{f.name}</h2><p>{f.address||"ยังไม่ได้ระบุที่อยู่"}{f.areaRai?` · ${f.areaRai} ไร่`:""}</p><strong>{f.plotCount} แปลง · {f.treeCount} ต้น</strong><button onClick={()=>go("trees")}>เปิดทะเบียนต้น →</button></article>)}</div>{!farms.length&&<EmptyCard headline="ยังไม่มีข้อมูลสวน" detail="กรุณาติดต่อผู้ดูแลระบบเพื่อตรวจการตั้งค่าเริ่มต้น"/>}{farms.length>0&&farms.every(x=>x.plotCount===0)&&<EmptyCard headline="มีข้อมูลสวนแล้ว แต่ยังไม่มีแปลง" detail="การเพิ่มและแก้ไขแปลงจะเปิดใช้งานใน Production Upgrade P2"/>}</>}
function EmptyPage({title,headline,detail}:{title:string;headline:string;detail:string}){return <><PageHead eyebrow="ข้อมูลใช้งานจริง" title={title} detail="หน้าจอนี้ไม่แสดงข้อมูลตัวอย่างแล้ว"/><EmptyCard headline={headline} detail={detail}/></>}
function PageHead({eyebrow,title,detail}:{eyebrow:string;title:string;detail:string}){return <div className="head"><div><small>{eyebrow}</small><h1>{title}</h1><p>{detail}</p></div></div>}
function EmptyCard({headline,detail}:{headline:string;detail:string}){return <article className="empty-card"><i><Leaf/></i><h2>{headline}</h2><p>{detail}</p><span><ShieldCheck/> ไม่มีการสร้างข้อมูลสมมติในฐานข้อมูล</span></article>}
function MiniEmpty({text}:{text:string}){return <div className="mini-empty"><Leaf/><span>{text}</span></div>}
function UsersPage(){const [users,setUsers]=useState<Array<{id:string;name:string;username:string;role:string;isActive:number|boolean}>>([]),[loading,setLoading]=useState(true);useEffect(()=>{fetch("/api/admin/users",{cache:"no-store"}).then(r=>r.json()).then(x=>setUsers(x.users||[])).finally(()=>setLoading(false))},[]);return <><PageHead eyebrow="ADMIN · LOCAL ACCOUNTS" title="ผู้ใช้และสิทธิ์" detail="บัญชีจริงที่สร้างโดย Admin ไม่ใช้อีเมลหรือบัญชี ChatGPT"/><div className="permission-overview"><div><ShieldCheck/><p><b>Admin ควบคุมระบบทั้งหมด</b><span>การกำหนดสิทธิ์ละเอียดจะตรวจครบทั้งหน้าเว็บและเซิร์ฟเวอร์ใน P9</span></p></div><span>{users.length} บัญชี</span></div><div className="user-table"><div className="user-head"><span>ผู้ใช้</span><span>บทบาท</span><span>สถานะ</span><span/><span/></div>{loading?<div className="mini-empty"><Leaf/>กำลังโหลดผู้ใช้...</div>:users.map(u=><div className="user-row" key={u.id}><span><i>{u.name.slice(0,2)}</i><b>{u.name}<small>@{u.username}</small></b></span><span>{u.role==="admin"?"Admin":"User"}</span><em className={u.isActive?"good":"pending"}>{u.isActive?"ใช้งาน":"ระงับ"}</em><span/><button disabled>🔒</button></div>)}</div></>}
