"use client";
import "./p3.css";
import {useEffect,useState} from "react";
import {Archive,CalendarDays,Check,ChevronRight,Flag,Leaf,Plus,Target,X} from "lucide-react";

type Farm={id:string;name:string};
type Season={id:string;farmId:string;farmName:string;name:string;startDate:string;endDate:string|null;status:string;targetKg:number|null;budget:number|null;actualKg:number|null;summary:string|null;currentStage:string|null;workCount:number;expense:number;harvestKg:number};
type Stage={id:string;name:string;sequence:number;status:string;startedOn:string|null;completedOn:string|null;note:string|null};
const call=async(url:string,init?:RequestInit)=>{const r=await fetch(url,init),x=await r.json();if(!r.ok)throw new Error(x.error||"ดำเนินการไม่สำเร็จ");return x};
const number=(value:number|null)=>new Intl.NumberFormat("th-TH").format(Number(value||0));

export function SeasonsPage({farms,refreshOverview}:{farms:Farm[];refreshOverview:()=>void}){
 const [seasons,setSeasons]=useState<Season[]>([]),[active,setActive]=useState<Season|null>(null),[stages,setStages]=useState<Stage[]>([]),[loading,setLoading]=useState(true),[modal,setModal]=useState<"create"|"close"|null>(null),[message,setMessage]=useState("");
 const load=()=>{setLoading(true);call("/api/seasons").then(x=>{setSeasons(x.seasons||[]);setActive(x.active||null);setStages(x.activeStages||[])}).catch(e=>setMessage(e.message)).finally(()=>setLoading(false))};useEffect(load,[]);
 const advance=async()=>{if(!active)return;setMessage("");try{const x=await call("/api/seasons",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"advance",seasonId:active.id})});setMessage(x.nextStage?`เลื่อนไประยะ “${x.nextStage}” แล้ว`:"ครบทุกระยะแล้ว สามารถปิดฤดูได้");load();refreshOverview()}catch(e){setMessage((e as Error).message)}};
 if(loading)return <div className="loading-panel"><Leaf/> กำลังโหลดฤดูการผลิต...</div>;
 const completed=stages.filter(x=>x.status==="completed").length,progress=stages.length?Math.round((completed/stages.length)*100):0,history=seasons.filter(x=>x.status==="closed");
 return <><div className="head p3-head"><div><small>PRODUCTION UPGRADE P3</small><h1>ฤดูการผลิต</h1><p>เปิดฤดู เชื่อมระยะงานและต้นทุน แล้วปิดเก็บเป็นประวัติถาวร</p></div>{!active&&<button className="primary" onClick={()=>setModal("create")}><Plus/> เปิดฤดูใหม่</button>}</div>{message&&<p className="p3-message">{message}</p>}{active?<><section className="p3-current"><div><em>กำลังดำเนินการ</em><h2>{active.name}</h2><p>{active.farmName} · เริ่ม {active.startDate}{active.endDate?` · เป้าหมายสิ้นสุด ${active.endDate}`:""}</p><span>ระยะปัจจุบัน <b>{active.currentStage||"ครบทุกระยะ"}</b></span></div><strong>{progress}%</strong><i><b style={{width:`${progress}%`}}/></i></section><div className="p3-stats"><article><Target/><span>เป้าหมายผลผลิต<b>{number(active.targetKg)} กก.</b></span></article><article><Flag/><span>งบประมาณ<b>฿{number(active.budget)}</b></span></article><article><CalendarDays/><span>งานที่เชื่อมฤดู<b>{number(active.workCount)} งาน</b></span></article></div><section className="p3-stages"><div className="p3-section-title"><div><h2>ระยะการผลิต</h2><p>ประวัติวันเริ่มและวันสิ้นสุดของแต่ละระยะจะไม่ถูกลบ</p></div><button onClick={advance} disabled={!active.currentStage}>เลื่อนไประยะถัดไป <ChevronRight/></button></div><div>{stages.map(s=><article className={s.status} key={s.id}><i>{s.status==="completed"?<Check/>:s.sequence}</i><span><b>{s.name}</b><small>{s.completedOn?`เสร็จ ${s.completedOn}`:s.startedOn?`เริ่ม ${s.startedOn}`:"รอดำเนินการ"}</small></span><em>{s.status==="completed"?"เสร็จแล้ว":s.status==="active"?"ปัจจุบัน":"รอ"}</em></article>)}</div></section><button className="p3-close-season" onClick={()=>setModal("close")}><Archive/> ปิดฤดูและเก็บเป็นประวัติ</button></>:<section className="p3-empty"><i><Leaf/></i><h2>ยังไม่มีฤดูที่กำลังดำเนินการ</h2><p>เปิดฤดูใหม่เพื่อเชื่อมงาน รายจ่าย คลัง และผลผลิตให้อยู่ในรอบเดียวกัน</p><button className="primary" onClick={()=>setModal("create")}><Plus/> เปิดฤดูการผลิต</button></section>}<section className="p3-history"><div className="p3-section-title"><div><h2>ประวัติฤดูก่อนหน้า</h2><p>ข้อมูลฤดูที่ปิดแล้วเก็บแบบอ่านย้อนหลัง ไม่ถูกนำมาปนกับฤดูใหม่</p></div><span>{history.length} ฤดู</span></div>{history.length?history.map(s=><article key={s.id}><Archive/><span><b>{s.name}</b><small>{s.farmName} · {s.startDate} ถึง {s.endDate||"-"}</small></span><span>ผลผลิตจริง<b>{number(s.actualKg||s.harvestKg)} กก.</b></span><span>ต้นทุนที่เชื่อม<b>฿{number(s.expense)}</b></span></article>):<div className="p3-no-history">ยังไม่มีประวัติฤดูที่ปิดแล้ว</div>}</section>{modal==="create"&&<CreateSeason farms={farms} close={()=>setModal(null)} saved={()=>{setModal(null);setMessage("เปิดฤดูการผลิตเรียบร้อยแล้ว");load();refreshOverview()}}/>}{modal==="close"&&active&&<CloseSeason season={active} close={()=>setModal(null)} saved={()=>{setModal(null);setMessage("ปิดฤดูและเก็บเป็นประวัติเรียบร้อยแล้ว");load();refreshOverview()}}/>}</>
}

function CreateSeason({farms,close,saved}:{farms:Farm[];close:()=>void;saved:()=>void}){const [farmId,setFarmId]=useState(farms[0]?.id||""),[name,setName]=useState(""),[startDate,setStart]=useState(new Date().toISOString().slice(0,10)),[endDate,setEnd]=useState(""),[targetKg,setTarget]=useState(""),[budget,setBudget]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");const submit=async()=>{setBusy(true);setError("");try{await call("/api/seasons",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"create",farmId,name,startDate,endDate,targetKg:Number(targetKg)||null,budget:Number(budget)||null})});saved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};return <Modal title="เปิดฤดูการผลิตใหม่" close={close}><label>สวน<select value={farmId} onChange={e=>setFarmId(e.target.value)}>{farms.map(f=><option value={f.id} key={f.id}>{f.name}</option>)}</select></label><label>ชื่อฤดู<input value={name} onChange={e=>setName(e.target.value)} placeholder="เช่น ฤดู 2570/71" autoFocus/></label><div className="p3-form-grid"><label>วันเริ่มต้น<input type="date" value={startDate} onChange={e=>setStart(e.target.value)}/></label><label>เป้าหมายสิ้นสุด<input type="date" value={endDate} onChange={e=>setEnd(e.target.value)}/></label><label>เป้าหมายผลผลิต (กก.)<input inputMode="decimal" value={targetKg} onChange={e=>setTarget(e.target.value)}/></label><label>งบประมาณ (บาท)<input inputMode="decimal" value={budget} onChange={e=>setBudget(e.target.value)}/></label></div><p className="p3-note"><Check/> ระบบจะสร้าง 10 ระยะมาตรฐานและเริ่มที่ “พักต้น”</p>{error&&<p className="p3-error">{error}</p>}<Actions close={close} save={submit} disabled={!farmId||!name||!startDate||busy} busy={busy} label="เปิดฤดู"/></Modal>}
function CloseSeason({season,close,saved}:{season:Season;close:()=>void;saved:()=>void}){const [endDate,setEnd]=useState(new Date().toISOString().slice(0,10)),[actualKg,setActual]=useState(String(season.harvestKg||"")),[summary,setSummary]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");const submit=async()=>{setBusy(true);setError("");try{await call("/api/seasons",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"close",seasonId:season.id,endDate,actualKg:Number(actualKg)||null,summary})});saved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};return <Modal title={`ปิด ${season.name}`} close={close}><p className="p3-warning">เมื่อปิดแล้ว ฤดูนี้จะเปลี่ยนเป็นประวัติและไม่สามารถเพิ่มงานใหม่เข้าไปได้ ข้อมูลเดิมจะยังอยู่ครบ</p><div className="p3-form-grid"><label>วันสิ้นสุด<input type="date" value={endDate} onChange={e=>setEnd(e.target.value)}/></label><label>ผลผลิตจริง (กก.)<input inputMode="decimal" value={actualKg} onChange={e=>setActual(e.target.value)}/></label></div><label>สรุปฤดู<textarea rows={4} value={summary} onChange={e=>setSummary(e.target.value)} placeholder="ผลลัพธ์ ปัญหา และสิ่งที่ควรปรับในฤดูถัดไป"/></label>{error&&<p className="p3-error">{error}</p>}<Actions close={close} save={submit} disabled={!endDate||busy} busy={busy} label="ยืนยันปิดฤดู"/></Modal>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="backdrop"><div className="modal p3-modal"><button className="close" onClick={close}><X/></button><small>PRODUCTION UPGRADE P3</small><h2>{title}</h2>{children}</div></div>}
function Actions({close,save,disabled,busy,label}:{close:()=>void;save:()=>void;disabled:boolean;busy:boolean;label:string}){return <div className="p3-modal-actions"><button onClick={close}>ยกเลิก</button><button className="primary" onClick={save} disabled={disabled}><Check/>{busy?"กำลังบันทึก...":label}</button></div>}
