"use client";
import Image from "next/image";
import {useState} from "react";
import {Home,Map,Trees,CalendarDays,WalletCards,FileText,Package,Plus,CloudRain,Check,QrCode,Leaf,TrendingUp,TrendingDown,X,Search} from "lucide-react";

type Tab="today"|"farms"|"trees"|"work"|"season"|"money"|"report"|"stock";
const menu:[Tab,string,typeof Home][]=[["today","วันนี้",Home],["farms","สวน/แปลง",Map],["trees","ทะเบียนต้น",Trees],["work","งาน & ปฏิทิน",CalendarDays],["season","ฤดูผลิต",Leaf],["money","บัญชี",WalletCards],["report","รายงาน",FileText],["stock","คลัง Phase 2",Package]];
const treeData=[{id:"DUR-A-001",v:"หมอนทอง",age:"6 ปี 4 เดือน",phase:"ติดผล",status:"สมบูรณ์"},{id:"DUR-A-002",v:"หมอนทอง",age:"6 ปี 4 เดือน",phase:"ติดผล",status:"เฝ้าระวัง"},{id:"DUR-B-014",v:"ชะนี",age:"4 ปี 8 เดือน",phase:"แตกใบอ่อน",status:"สมบูรณ์"}];
const fmt=(n:number)=>new Intl.NumberFormat("th-TH").format(n);
export default function App(){
 const [tab,setTab]=useState<Tab>("today"),[farm,setFarm]=useState("สวนศรีจันทร์"),[modal,setModal]=useState(false),[kind,setKind]=useState("งาน"),[title,setTitle]=useState(""),[toast,setToast]=useState("");
 const [tasks,setTasks]=useState([{id:1,t:"ตรวจดอกและแมลง",s:"แปลง A · 48 ต้น",done:false},{id:2,t:"ให้น้ำโซนเหนือ",s:"แปลง A · 24 ต้น",done:true},{id:3,t:"ใส่ปุ๋ย 15-15-15",s:"แปลง B · 32 ต้น",done:false}]);
 const save=()=>{if(kind==="งาน"&&title)setTasks(x=>[{id:Date.now(),t:title,s:"แปลง A",done:false},...x]);setModal(false);setTitle("");setToast("บันทึกเรียบร้อยแล้ว");setTimeout(()=>setToast(""),2200)};
 return <div className="shell"><aside><button className="brand" onClick={()=>setTab("today")}><b><Leaf/></b><span><strong>น้องทุเรียน</strong><small>Durian Smart Farm</small></span></button><nav>{menu.map(([id,label,I])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}><I/>{label}</button>)}</nav><div className="season-mini"><small>ฤดู 2569/70</small><strong>ติดผล · วันที่ 64/110</strong><i><b/></i></div></aside><main><header><select value={farm} onChange={e=>setFarm(e.target.value)}><option>สวนศรีจันทร์</option><option>สวนริมคลอง</option></select><label><Search/><input placeholder="ค้นหาต้น งาน หรือรายการเงิน"/></label><button className="primary" onClick={()=>setModal(true)}><Plus/> เพิ่มรายการ</button></header><section className="content">
 {tab==="today"&&<Dashboard farm={farm} tasks={tasks} setTasks={setTasks} go={setTab} add={()=>setModal(true)}/>} 
 {tab==="farms"&&<Farms go={setTab}/>} {tab==="trees"&&<TreesPage/>} {tab==="work"&&<Work tasks={tasks} setTasks={setTasks} add={()=>setModal(true)}/>} {tab==="season"&&<Season/>} {tab==="money"&&<Money add={()=>setModal(true)}/>} {tab==="report"&&<Report/>} {tab==="stock"&&<Stock/>}
 </section></main><div className="mobile-nav">{menu.slice(0,5).map(([id,label,I])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}><I/><span>{label.split(" ")[0]}</span></button>)}<button className="fab" onClick={()=>setModal(true)}><Plus/></button></div>
 {modal&&<div className="backdrop"><div className="modal"><button className="close" onClick={()=>setModal(false)}><X/></button><small>QUICK ADD</small><h2>เพิ่มรายการใหม่</h2><div className="types">{["งาน","รายจ่าย","รายรับ"].map(k=><button className={kind===k?"active":""} onClick={()=>setKind(k)} key={k}>{k}</button>)}</div><label>ชื่อรายการ<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder={kind==="งาน"?"เช่น ตรวจดอกแปลง A":"เช่น ซื้อปุ๋ย"}/></label>{kind!=="งาน"&&<label>จำนวนเงิน (บาท)<input inputMode="decimal" placeholder="0.00"/></label>}<div className="formrow"><label>พื้นที่ / หมวด<select><option>{kind==="งาน"?"แปลง A":"ปุ๋ย"}</option><option>{kind==="งาน"?"แปลง B":"ค่าแรง"}</option></select></label><label>วันที่<input type="date" defaultValue="2026-09-27"/></label></div><button className="primary save" onClick={save}><Check/> บันทึก</button></div></div>}{toast&&<div className="toast"><Check/>{toast}</div>}</div>
}
const Head=({k,t,d,action}:{k:string,t:string,d:string,action?:React.ReactNode})=><div className="head"><div><small>{k}</small><h1>{t}</h1><p>{d}</p></div>{action}</div>;
function Dashboard({farm,tasks,setTasks,go,add}:{farm:string,tasks:any[];setTasks:any;go:any;add:()=>void}){return <><div className="hello"><div><small>อาทิตย์ 27 กันยายน 2569</small><h1>สวัสดีครับ คุณสมชาย 👋</h1><p>มี 2 งานรอทำ และ 1 ต้นที่ต้องเฝ้าระวัง</p></div><span><CloudRain/>28° <small>ฝน 60%</small></span></div><div className="hero"><div><em>ศูนย์บัญชาการสวนวันนี้</em><h2>เริ่มเช้าให้เป็นระบบ<br/>ดูแลงานสำคัญก่อน</h2><p>{farm} · ฤดู 2569/70 · ระยะติดผล</p><button className="light" onClick={add}><Plus/> เพิ่มงานด่วน</button></div><Image src="/nong-durian.png" alt="น้องทุเรียน" width={300} height={300}/></div><div className="stats"><Card icon={<Trees/>} k="ต้นทุเรียน" v="128" d="สมบูรณ์ 124 ต้น"/><Card icon={<CalendarDays/>} k="งานวันนี้" v="3" d="เสร็จแล้ว 1 งาน"/><Card icon={<TrendingUp/>} k="รายรับเดือนนี้" v="฿128,400" d="+18.4%"/><Card icon={<TrendingDown/>} k="รายจ่ายเดือนนี้" v="฿8,030" d="เฉลี่ย ฿62/ต้น"/></div><div className="grid"><article className="panel"><Title t="งานวันนี้" a="ดูปฏิทิน" click={()=>go("work")}/>{tasks.map(x=><div className="task" key={x.id}><button className={x.done?"checked":""} onClick={()=>setTasks((a:any[])=>a.map(y=>y.id===x.id?{...y,done:!y.done}:y))}>{x.done&&<Check/>}</button><p><b>{x.t}</b><small>{x.s}</small></p><time>วันนี้</time></div>)}<button className="add" onClick={add}><Plus/> เพิ่มงานใหม่</button></article><article className="panel"><Title t="เงินเข้า–ออกเดือนนี้" a="ดูบัญชี" click={()=>go("money")}/><div className="balance"><small>กระแสเงินสดสุทธิ</small><b>฿120,370</b><span>รายรับ ฿128,400 · รายจ่าย ฿8,030</span></div><div className="chart"><i/><i/><i/><i/><i/><i/></div></article></div></>}
function Card({icon,k,v,d}:{icon:any;k:string;v:string;d:string}){return <article className="card"><b>{icon}</b><div><small>{k}</small><strong>{v}</strong><span>{d}</span></div></article>};function Title({t,a,click}:{t:string;a:string;click:()=>void}){return <div className="title"><h3>{t}</h3><button onClick={click}>{a} →</button></div>}
function Farms({go}:{go:any}){return <><Head k="USER › FARM › PLOT › TREE" t="สวนของฉัน" d="จัดการหลายสวน แปลง และต้นทุเรียนจากที่เดียว"/><div className="farmgrid">{[["สวนศรีจันทร์","24 ไร่","2 แปลง · 128 ต้น"],["สวนริมคลอง","8 ไร่","1 แปลง · 42 ต้น"]].map((x,i)=><article className="farm" key={x[0]}><Map/><small>{i?"สวนรอง":"สวนหลัก"}</small><h2>{x[0]}</h2><p>อ.ขลุง จ.จันทบุรี · {x[1]}</p><strong>{x[2]}</strong><button onClick={()=>go("trees")}>เปิดทะเบียนต้น →</button></article>)}</div><h3>แปลงในสวนศรีจันทร์</h3><div className="plots"><Plot n="แปลง A · โซนเหนือ" d="72 ต้น · หมอนทอง" p="78%"/><Plot n="แปลง B · โซนใต้" d="56 ต้น · ชะนี/ก้านยาว" p="52%"/></div></>};function Plot({n,d,p}:{n:string;d:string;p:string}){return <article className="plot"><div>{[1,2,3,4,5,6,7,8].map(i=><i key={i}/>)}</div><h3>{n}</h3><p>{d}</p><span>ความพร้อมฤดูผลิต <b>{p}</b></span></article>}
function TreesPage(){const [q,setQ]=useState("");return <><Head k="128 ต้น · 3 พันธุ์" t="ทะเบียนต้นทุเรียน" d="Durian ID เชื่อม QR รูปภาพ สถานะ ระยะผลิต และ Timeline" action={<button className="primary"><Plus/> เพิ่มต้น</button>}/><div className="filter"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ค้นหา Durian ID หรือพันธุ์"/><button><QrCode/> สแกน QR</button></div><div className="table">{treeData.filter(x=>(x.id+x.v).toLowerCase().includes(q.toLowerCase())).map(x=><article key={x.id}><span><Leaf/><b>{x.id}<small>แปลง {x.id.split("-")[1]}</small></b></span><span>{x.v}<small>{x.age}</small></span><em>{x.phase}</em><span className={x.status==="เฝ้าระวัง"?"warn":"ok"}>● {x.status}</span><button>Timeline →</button></article>)}</div></>}
function Work({tasks,setTasks,add}:{tasks:any[];setTasks:any;add:()=>void}){return <><Head k="กันยายน 2569" t="งานในสวน & ปฏิทิน" d="Quick Add วางแผน มอบหมาย และเชื่อมรายจ่ายโดยไม่ซ้ำ" action={<button className="primary" onClick={add}><Plus/> เพิ่มงาน</button>}/><div className="grid"><article className="panel calendar"><h3>กันยายน 2569</h3><div>{["อา","จ","อ","พ","พฤ","ศ","ส",...Array.from({length:30},(_,i)=>String(i+1))].map((x,i)=><span className={x==="27"?"sel":i<7?"day":""} key={i}>{x}</span>)}</div></article><article className="panel"><Title t="งานวันที่ 27" a={`${tasks.length} รายการ`} click={()=>{}}/>{tasks.map(x=><div className="task" key={x.id}><button className={x.done?"checked":""} onClick={()=>setTasks((a:any[])=>a.map(y=>y.id===x.id?{...y,done:!y.done}:y))}>{x.done&&<Check/>}</button><p><b>{x.t}</b><small>{x.s}</small></p></div>)}</article></div></>}
function Season(){return <><Head k="ฤดู 2569/70" t="ฤดูการผลิต" d="เชื่อมต้น งาน และต้นทุนครบวงจร"/><div className="season"><em>กำลังดำเนินการ</em><h2>ระยะติดผลและบำรุงผล</h2><p>วันที่ 64 จาก 110 · คาดเก็บเกี่ยว 12 พฤศจิกายน 2569</p><i><b/></i><strong>58%</strong></div><div className="steps">{["พักต้น","แตกใบอ่อน","สะสมอาหาร","ออกดอก","ติดผล","เก็บเกี่ยว"].map((x,i)=><span className={i<5?"done":""} key={x}><b>{i<4?"✓":i+1}</b>{x}</span>)}</div></>}
function Money({add}:{add:()=>void}){return <><Head k="บัญชีสวน" t="รายรับ–รายจ่าย" d="รองรับปุ๋ย ยา/สาร/ธาตุอาหาร ค่าแรง วัสดุ อุปกรณ์ น้ำมัน ไฟ ระบบน้ำ ซ่อม ขนส่ง และหมวดเอง" action={<button className="primary" onClick={add}><Plus/> บันทึกรายการ</button>}/><div className="stats"><Card icon={<TrendingUp/>} k="รายรับ" v="฿128,400" d="กันยายน"/><Card icon={<TrendingDown/>} k="รายจ่าย" v="฿8,030" d="กันยายน"/><Card icon={<WalletCards/>} k="สุทธิ" v="฿120,370" d="อัตรากำไร 93.7%"/></div><div className="panel list"><Title t="รายการล่าสุด" a="ส่งออก" click={()=>{}}/>{[["ขายทุเรียนหมอนทอง","ผลผลิต",128400,1],["ปุ๋ย 15-15-15","ปุ๋ย",4650,-1],["ค่าแรงตัดหญ้า","ค่าแรงรายวัน",2400,-1],["น้ำมันเครื่องสูบน้ำ","น้ำมัน",980,-1]].map(x=><div key={String(x[0])}><p><b>{x[0]}</b><small>{x[1]} · แนบใบเสร็จได้</small></p><strong className={Number(x[3])>0?"plus":"minus"}>{Number(x[3])>0?"+":"-"}฿{fmt(Number(x[2]))}</strong></div>)}</div></>}
function Report(){return <><Head k="ฤดู 2569/70" t="รายงานต้นทุน" d="แยกตามหมวด สวน แปลง ฤดู และต้น"/><div className="stats"><Card icon={<WalletCards/>} k="ต้นทุนฤดูนี้" v="฿248,560" d="59.2% ของงบ"/><Card icon={<Trees/>} k="เฉลี่ย/ต้น" v="฿2,390" d="104 ต้น"/><Card icon={<FileText/>} k="คาดการณ์/กก." v="฿29.24" d="เป้า 8,500 กก."/></div><div className="panel report"><h3>ต้นทุนตามหมวด</h3>{[["ปุ๋ย",48],["ค่าแรง",25],["ยา/ธาตุอาหาร",15],["อื่นๆ",12]].map(x=><p key={String(x[0])}><span>{x[0]} <b>{x[1]}%</b></span><i><b style={{width:`${x[1]}%`}}/></i></p>)}</div></>}
function Stock(){return <><Head k="เตรียมพร้อม PHASE 2" t="คลังปัจจัยการผลิตและวัสดุสิ้นเปลือง" d="สต๊อกปุ๋ย ยา สารป้องกันศัตรูพืช ฮอร์โมน ธาตุอาหาร และวัสดุใช้งานในสวน"/><div className="stock"><Package/><div><em>Schema พร้อมแล้ว</em><h2>รับเข้า · เบิกใช้ · ปรับยอด · Lot · วันหมดอายุ</h2><p>รองรับหน่วยนับ ผู้ขาย จุดสั่งซื้อขั้นต่ำ และเชื่อมการเบิกกับงาน/แปลง/ฤดู เพื่อสร้างต้นทุนและรายจ่ายเพียงครั้งเดียว</p><div>{["ปุ๋ย","ยา/สาร","ฮอร์โมน","ธาตุอาหาร","วัสดุสิ้นเปลือง","อะไหล่","น้ำมัน"].map(x=><span key={x}>{x}</span>)}</div></div></div></>}
